version: "3"
services:
  django:
    build:
      context: backend
      dockerfile: Dockerfile
    image: trumio-team-40-server
    container_name: trumio-team-40-django
    restart: unless-stopped
    # env_file: .env
    environment:
      # - DB_HOST=postgresqldb
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 8888:8888
    volumes:
      - ./backend:/app
    # depends_on:
    #   - postgresqldb
    networks:
      - app-network
    command:
      - /bin/sh
      - -c
      - |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8888
  # postgresqldb:
  #   image: 'bitnami/postgresql:latest'
  #   container_name: trumio-team-40-postgresqldb
  #   restart: unless-stopped
  #   env_file: .env
  #   environment:
  #     - POSTGRESQL_USERNAME=$DB_USER
  #     - POSTGRESQL_PASSWORD=$DB_PASSWORD
  #     - POSTGRESQL_DATABASE=$DB_NAME
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U $DB_USER"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   volumes:
  #     - dbdata:/bitnami/postgresql
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
